### PR TITLE
Update layout of UpdateView with links

### PR DESCRIPTION
**Pull request by zeebok**
This addresses #106 and includes similar links as the welcome view.

### CODE REVIEW

**Comment by jeremypw** [comment]
@zeebok  There seems to have been a lot of changes to Onboarding since this was started - is it still needed?  If so, it would be helpful to post "Before" and "After" screenshots.

**Comment by zeebok** [comment]
@jeremypw Through all of the updates, the page that is affected hasn't changed so I think this PR is still relevant.
Before:
Screenshot from 2021-07-29 02-52-51
After:
Screenshot from 2021-07-29 02-52-41

**Comment by jeremypw** [comment]
Hmm thats odd :thinking:  After installing master from source and running `gsettings reset io.elementary.onboarding viewed; io.elementary.onboarding`  I got a different view with more pages - none like the above.  However after *rebooting* and logging in again I do get the three page view so it seems I was getting confused between the post-install and the post-update views.  Sorry for the confusion. Maybe the README.md needs to clarify this.

**Comment by zeebok** [comment]
I do wonder if I should add the Community Support link to the What's New page as well. @cassidyjames what do you think?

**Comment by ahoneybun** [comment]
I feel like 3 items is pretty nice and even when it comes to sizing though if we need/want to add more 5 would be the next nice number.

**Pull request closed without merging**
