### PR TITLE
Hide Night Light on unsupported hardware

### LINKED ISSUE #115: Hide Night Light on unsupported hardware
Counterpart to https://github.com/elementary/switchboard-plug-display/issues/272

### PR DESCRIPTION
**Pull request by meisenzahl**
Closes https://github.com/elementary/onboarding/issues/115

### CODE REVIEW

**Comment by cassidyjames** [comment]
@davidmhewitt had mentioned in Slack there is probably a better way to do this like checking the GPU drivers, I think?

**Comment by davidmhewitt** [comment]
Yeah, I didn't spend looking into it, but this feels like a hack we'll forget about and wonder why stuff isn't working in the future. I'd ideally like to find a better solution.

**Comment by meisenzahl** [comment]
I am aware that configuring based on the processor architecture is not the best solution.

We may be able to fix this upstream 🤔

If I see it right, you could ask [here](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/3bd47c0cfc5de40f4688443a2696c8a2d1033493/plugins/color/gsd-color-state.c#L492) if Night Light is supported or not. In case of an error, one could disable a D-BUS property.

**Comment by meisenzahl** [comment]
I created an issue in [gnome-settings-daemon](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/580)

**Pull request closed without merging**
