### PR TITLE
WelcomeView: add images and left align links

### PR DESCRIPTION
**Pull request by danrabbit**
Screenshot from 2019-04-16 19 14 29@2x

### CODE REVIEW

**Comment by danrabbit** [comment]
Screenshot from 2019-04-17 12 33 13@2x

Yeah it looks weird to me to have essentially a bulleted list center aligned

**Comment by cassidyjames** [comment]
@danrabbit ah yeah I agree. I'm still not sure how I'd improve it, though. It just feels off left-aligned; it's possible it's due to the large variance in length of text? I'm not sure. :grimacing:

**Comment by danrabbit** [comment]
Screenshot from 2019-04-17 12 44 14@2x

How about changing the labels?

**Comment by cassidyjames** [comment]
@danrabbit yeah I can dig it. If I can put my finger on any other improvements we can always try them later.

**Pull request merged**
