### PR TITLE
Improve screenreader support

### PR DESCRIPTION
**Pull request by danirabbit**
Keyboard nav is still pretty trash, but at least everything should be read out correctly now

### CODE REVIEW

**Comment by jeremypw** [comment]
I could not get this to work with the built-in screenreader - hovering the mouse over various controls produced no sound and spammed the terminal with `Screen coordinates not supported, reported positions will be wrong` (the same error messages produced in `master`).  Running other apps that do work with the screenreader in a terminal did not produce such messages.

**Review by jeremypw — APPROVED** [review]

**Comment by danirabbit** [comment]
@jeremypw ive never seen a feature where the screen reader reacts to mouse hovering. Can you give more information about where this works or how to enable it?

**Comment by jeremypw** [comment]
@danirabbit It works pretty much everywhere for me on the elementary interface if you switch the screenreader on in Accessibility settings or press <Super><Alt>S. Admittedly its pretty annoying but I only switched it on for testing.

**Comment by jeremypw** [comment]
It may be reading tooltips come to think of it....

**Comment by jeremypw** [comment]
Some buttons only produce sound *after* you click them which, I imagine, is not very useful.  But there are exception - like the "Open Folder" button in Code - which does not have a tooltip but nevertheless produces sound on hovering.

**Pull request merged**
