### PR TITLE
Redesign app icon

### PR DESCRIPTION
**Pull request by danirabbit**
For this one I decided to add gloss because I want to convey an idea of new-ness. It's shiny, it's brand new! Welcome to your shiny, new OS

And I thought it would be a nice touch to use this on the last screen instead of just the regular process-completed icon:

## BEFORE
Screenshot from 2023-03-28 15 36 09

## AFTER
Screenshot from 2023-03-28 15 35 20

### CODE REVIEW

**Comment by danirabbit** [comment]
@lenemter sounds like you have thoughts 😅

**Review by micahilbery — APPROVED** [review]
It's more consistent with the new direction the icons are going both in the shape and the checkmark style. LGTM! :+1:

**Comment by lenemter** [comment]
@danirabbit The new icon looks nice, but IMO process-completed emblem fits better for FinishView.

**Comment by meisenzahl** [comment]
Sorry for joining the discussion so late.

Since the proposed icon will also be the app icon, I wonder if the difference from the Tasks icon is significant enough:

| Onboarding | Tasks |
|---|---|
|  |  |

**Comment by danirabbit** [comment]
@lenemter reverted

@meisenzahl I'm not super worried about it since this icon isn't shown in the applications menu. But yeah it would be nice to figure out some better differentiation in the future I think

**Pull request merged**
