### PR TITLE
Housekeeping: Bind number of days to setting

### LINKED ISSUE #59: Housekeeping: Bind number of days to setting
Like we did in https://github.com/elementary/switchboard-plug-security-privacy/pull/76

If someone opens the settings and changes it, we should keep the Onboarding view accurate.

### PR DESCRIPTION
**Pull request by lenemter**
Closes #59

### CODE REVIEW

**Review by jeremypw — APPROVED** [review]
Works as expected - thanks!

**Comment by danrabbit** [comment]
Build is failing due to container problems, so I'm gonna override and merge as admin

**Comment by lenemter** [comment]
@danirabbit can you update pot files here too, please?

**Comment by danirabbit** [comment]
@lenemter done!

**Pull request merged**
