### PR TITLE
AppCenterView: Mention Flatpak and Flathub

### PR DESCRIPTION
**Pull request by cassidyjames**
Might not want to link directly there, idk.

Screenshot from 2020-06-25 18 38 07

### CODE REVIEW

**Comment by danrabbit** [comment]
I'm happy with this solution. It's a good middle ground without actually including Flatpak out of the box but letting people know where they can find more apps.

Do you think it's downplaying it too much to use a small label as well?

Screenshot from 2020-06-25 18 19 39@2x

**Comment by cassidyjames** [comment]
Ah yeah I was gonna make it small and forgot. 👍

**Comment by cassidyjames** [comment]
Another thought. What if in addition or instead, we make Sideload handle opening .deb files just so we can say we don't support opening them. :sweat_smile: And then include a message like this in that view in Sideload.

**Comment by danrabbit** [comment]
@cassidyjames can you open an issue there and we can discuss on the sideload issue tracker?

**Comment by cassidyjames** [comment]
Fixes #99

**Pull request merged**
