### PR TITLE
Utils: use GLib.get_os_info

### LINKED ISSUE #85: Use GLib.get_os_release
## Describe the bug
Exactly the same as https://github.com/elementary/switchboard-plug-about/issues/112.
The same code is just copied here.

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #85

### CODE REVIEW

**Comment by worldofpeace** [comment]
Not related to this PR, but with https://github.com/elementary/onboarding/pull/45, it seems a bit weird if you use this not on elementary OS. 

This is on nixos for example, and it links to the elementary OS blog:
Screenshot from 2020-07-03 14 08 39

**Comment by danrabbit** [comment]
I'm inclined to think in this case it still makes sense to link upstream to our blog and get involved pages for changes to Pantheon. What are your thoughts @cassidyjames ?

**Comment by jeremypw** [comment]
Requires libhandy-1 version >=1.0

**Comment by danrabbit** [comment]
@jeremypw onboarding does yes, this branch doesn't introduce a new handy dep

**Comment by cassidyjames** [comment]
@danrabbit yeah I'm mixed. I'm fine to defer to downstreams here and what they would expect. :shrug:

**Comment by cassidyjames** [comment]
Approving this because it's no worse than current master with regards to the downstream issue. I'd be open to a follow-up that does something differently for downstreams, though.

**Comment by worldofpeace** [comment]
> No worse than master; Can be addressed in a follow-up PR

I can open an issue to track it, because I still find it as a downstream user strange.

**Comment by cassidyjames** [comment]
@worldofpeace sounds good. :+1:

**Pull request merged**
